packages:
  - "apps/**"
  - "packages/**"
allowBuilds:
  esbuild: true
  unrs-resolver: true
savePrefix: ""
minimumReleaseAgeExclude:
  - "@alextheman/*"
  - alex-c-line
  - "alextheman231/github-actions/*"
ignoreWorkspaceRootCheck: true
overrides:
  typescript: 6.0.3
patchedDependencies:
  drizzle-kit: patches/drizzle-kit.patch
