name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
    types: [checks_requested]

permissions:
  contents: read

jobs:
  lexicon-ci:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: prisma
          POSTGRES_DB: tests
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgresql://postgres:prisma@localhost:5432/tests?schema=public

    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Use PNPM
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 22
          cache: "pnpm"

      - name: Cache Turborepo cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            .turbo
            apps/back-end/.turbo
            apps/front-end/.turbo
            packages/models/.turbo
          key: turbo-${{ hashFiles('{apps,packages}/**', 'package.json', 'pnpm-lock.yaml', 'pnpm-workspace.yaml', 'turbo.json') }}
          restore-keys: turbo-

      - name: Initialise environment variables
        run: |
          touch apps/back-end/.env.test
          echo DATABASE_URL="postgresql://postgres:prisma@localhost:5432/tests?schema=public" >> apps/back-end/.env.test
          echo API_BASE_URL="http://localhost:5432" >> apps/back-end/.env.test

      - name: Install dependencies
        run: pnpm install

      - name: Apply migrations
        run: pnpm run migrate-db
        working-directory: apps/back-end
        env:
          NODE_ENV: test

      - name: Build packages
        run: pnpm run build

      - name: Run linting checks
        run: pnpm run lint

      - name: Run tests
        run: pnpm test

  actions-ci:
    uses: alextheman231/github-actions/.github/workflows/actions-ci.yml@2e41fee3271c96b410b398994b6df72997e18c02 # v11.2.1
