name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
    types: [checks_requested]

permissions:
  contents: read

jobs:
  blog-site-ci:
    runs-on: ubuntu-latest
    # services:
    #   postgres:
    #     image: postgres:17
    #     env:
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: prisma
    #       POSTGRES_DB: tests
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    #     ports:
    #       - 5432:5432
    # env:
    #   DATABASE_URL: postgresql://postgres:prisma@localhost:5432/tests?schema=public

    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Use PNPM
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22
          cache: "pnpm"

      # - name: Initialise environment variables
      #   run: |
      #     rm -f apps/back-end/.env.test
      #     touch apps/back-end/.env.test
      #     touch apps/back-end/.env.development
      #     echo DATABASE_URL="postgresql://postgres:prisma@localhost:5432/tests?schema=public" >> apps/back-end/.env.test
      #     echo DATABASE_URL="postgresql://postgres:prisma@localhost:5432/tests?schema=public" >> apps/back-end/.env.development

      - name: Install dependencies
        run: pnpm install

      # - name: Generate Prisma Client
      #   run: |
      #     pnpm run migrate-deploy
      #     pnpm run generate --filter=back-end

      - name: Build packages
        run: pnpm run build

      - name: Run linting checks
        run: pnpm run lint

  actions-ci:
    uses: alextheman231/github-actions/.github/workflows/actions-ci.yml@dc2d1246a158a1a04045a85a8c1bfd1978afeaf2 # v10.1.0
