name: Deploy Production

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'alextheman231/lexicon' }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6

      - name: Build and push Docker image to ECR
        env:
          AWS_ECR_REPOSITORY_URL: ${{ vars.AWS_ECR_REPOSITORY_URL }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            -t "$AWS_ECR_REPOSITORY_URL:$IMAGE_TAG" \
            -t "$AWS_ECR_REPOSITORY_URL:latest" \
            .

          docker push "$AWS_ECR_REPOSITORY_URL:$IMAGE_TAG"
          docker push "$AWS_ECR_REPOSITORY_URL:latest"

      - name: Apply migrations
        id: migration
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_CLUSTER_NAME: ${{ vars.AWS_CLUSTER_NAME }}
          AWS_MIGRATION_TASK_FAMILY: ${{ vars.AWS_MIGRATION_TASK_FAMILY }}
          AWS_SECURITY_GROUP_ID: ${{ vars.AWS_SECURITY_GROUP_ID }}
          AWS_SUBNET_IDS: ${{ vars.AWS_SUBNET_IDS }}
          AWS_ASSIGN_PUBLIC_IP: ${{ vars.AWS_ASSIGN_PUBLIC_IP }}
        run: |
          TASK_ARN=$(aws ecs run-task \
            --cluster "$AWS_CLUSTER_NAME" \
            --task-definition "$AWS_MIGRATION_TASK_FAMILY" \
            --launch-type FARGATE \
            --network-configuration \
            "awsvpcConfiguration={subnets=[$AWS_SUBNET_IDS],securityGroups=[$AWS_SECURITY_GROUP_ID],assignPublicIp=$AWS_ASSIGN_PUBLIC_IP}" \
            --query 'tasks[0].taskArn' \
            --output text
          )

          if [ "$TASK_ARN" = "None" ]; then
            echo "Failed to start migration task."
            exit 1
          fi

          echo "task_arn=$TASK_ARN" >> "$GITHUB_OUTPUT"

      - name: Wait for migrations to apply successfully
        env:
          AWS_CLUSTER_NAME: ${{ vars.AWS_CLUSTER_NAME }}
          TASK_ARN: ${{ steps.migration.outputs.task_arn }}
        run: aws ecs wait tasks-stopped --cluster "$AWS_CLUSTER_NAME" --tasks "$TASK_ARN"

      - name: Return the exit code provided from the migration application
        env:
          AWS_CLUSTER_NAME: ${{ vars.AWS_CLUSTER_NAME }}
          TASK_ARN: ${{ steps.migration.outputs.task_arn }}
        run: |
          EXIT_CODE=$(
            aws ecs describe-tasks \
            --cluster "$AWS_CLUSTER_NAME" \
            --tasks "$TASK_ARN" \
            --query "tasks[0].containers[0].exitCode" \
            --output text
          )

          aws ecs describe-tasks \
            --cluster "$AWS_CLUSTER_NAME" \
            --tasks "$TASK_ARN" \
            --query 'tasks[0].{
              StopReason:stoppedReason,
              ExitCode:containers[0].exitCode,
              Reason:containers[0].reason,
              LastStatus:containers[0].lastStatus
            }'

          if [ "$EXIT_CODE" = "None" ]; then
            echo "Migration task stopped without reporting an exit code."
            exit 1
          fi

          exit "$EXIT_CODE"

      - name: Deploy ECS service
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_CLUSTER_NAME: ${{ vars.AWS_CLUSTER_NAME }}
          AWS_SERVICE_NAME: ${{ vars.AWS_SERVICE_NAME }}
        run: aws ecs update-service --cluster "$AWS_CLUSTER_NAME" --service "$AWS_SERVICE_NAME" --region "$AWS_REGION" --force-new-deployment

      - name: Wait for service to stabilise
        env:
          AWS_CLUSTER_NAME: ${{ vars.AWS_CLUSTER_NAME }}
          AWS_SERVICE_NAME: ${{ vars.AWS_SERVICE_NAME }}
        run: aws ecs wait services-stable --cluster "$AWS_CLUSTER_NAME" --service "$AWS_SERVICE_NAME"

  deploy-sentry:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'alextheman231/lexicon' }}
    permissions:
      contents: read
    env:
      SENTRY_RELEASE: ${{ github.sha }}
    needs: [deploy-app]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install PNPM
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 22
          cache: "pnpm"

      - name: Cache Turborepo cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: "**/.turbo"
          key: turbo-deploy-${{ hashFiles('{apps,packages}/**', 'package.json', 'pnpm-lock.yaml', 'pnpm-workspace.yaml', 'turbo.json') }}
          restore-keys: turbo-deploy-

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm run build

      - name: Create Sentry release for back-end
        uses: getsentry/action-release@ff07929a6537bac57790c3451cf4d364aca38528 # v3.7.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_ORGANISATION_TOKEN }}
          SENTRY_ORG: alextheman231
          SENTRY_PROJECT: lexicon-back-end
        with:
          environment: production
          release: ${{ env.SENTRY_RELEASE }}
          ignore_missing: true
          ignore_empty: true

      - name: Create Sentry release for front-end
        uses: getsentry/action-release@ff07929a6537bac57790c3451cf4d364aca38528 # v3.7.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_ORGANISATION_TOKEN }}
          SENTRY_ORG: alextheman231
          SENTRY_PROJECT: lexicon-front-end
        with:
          environment: production
          release: ${{ env.SENTRY_RELEASE }}
          sourcemaps: apps/front-end/dist/assets
          ignore_missing: true
          ignore_empty: true
