name: Scheduled Deployment

on:
  schedule:
    - cron: 0 9 * * 1

jobs:
  scheduled-deployment:
    permissions:
      contents: write
      pull-requests: write
    if: ${{ github.repository == 'alextheman231/lexicon' }}
    uses: alextheman231/github-actions/.github/workflows/create-change-request.yml@aa8a3ef9f3e8d4e820402e4f6bf811af5298c3a9 # v12.4.1
    with:
      APP_ID: ${{ vars.ALEX_UP_BOT_APP_ID }}
      actor: alex-up-bot[bot]
      reason: "Scheduled deployment"
      description: "This is a monthly scheduled deployment of Lexicon, intended to fix potential drifts. Please verify CI passes before merging."
      branch_name: scheduled-deployment
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.ALEX_UP_BOT_PRIVATE_KEY }}
